apiVersion: v1
kind: Pod
metadata:
  name: multi-container
  namespace: roboshop
spec:
  containers:
    - name: nginx-multi   # this is one container 
      image: nginx:latest
      ports:
       - 80
    - name: side-car # in the same pod this is another container
      image: alpine:latest