apiVersion: v1
kind: Pod
metadata:
  name: envar-demo
  namespace: roboshop
spec:
  containers:
  - name: envar-demo-container
    image: nginx
    envFrom:
    - configMapRef:
        name: config-practice    
