apiVersion: v1
kind: Pod
metadata:
  name: config-pod
  namespace: roboshop
spec:
  containers:
  - name: config-pod
    image: nginx
    env:
    - name: my_name
      valueFrom:
        configMapKeyRef:
          name: config-practice
          key: my_name  
    - name: Designation
      valueFrom:
        configMapKeyRef:
          name: config-practice
          key: designation
    - name: Company
      valueFrom:
        configMapKeyRef:
          name: config-practice
          key: company