FROM almalinux
LABEL container="nginx"
EXPOSE 80/tcp
RUN yum install nginx -y
RUN rm -rf /usr/share/nginx/html/index.html
COPY Roboshop_WebPage/ /usr/share/nginx/html
CMD [ "nginx", "-g", "daemon off;" ]